language: python
sudo: false

python:
- 2.7
- 3.3
- 3.4
- 3.5

env:
  matrix:
  - FLASK_VERSION=0.10.1
  # TODO: enable when future release is available:
  # http://flask.pocoo.org/docs/0.11/changelog/#version-0-10-2
  # - FLASK_VERSION=0.10.2
  - FLASK_VERSION=0.11.0

install:
- pip install -r requirements.txt
- pip install flask==${FLASK_VERSION}  # override version for the build matrix
- pip install coverage==3.6
- pip install python-coveralls==2.4.0
- export PYTHONPATH=.

before_script: coverage erase

script: ./runtests

after_success: coverage report; coveralls
